backend:
  name: github
  repo: hhhug000/blog
  branch: main
  base_url: 'https://hugo.haaxman.co.uk/oauth'

media_folder: 'src/content/blog/images'
public_folder: '/blog/images'

collections:
  - name: blog
    label: 'Blog Posts'
    folder: 'src/content/blog'
    create: true
    format: 'frontmatter'
    extension: 'md'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime', format: 'YYYY-MM-DD' }
      - { label: 'Published', name: 'published', widget: 'boolean', default: true }
      - { label: 'Hero Image', name: 'heroImage', widget: 'image', required: false }
      - { label: 'Author', name: 'author', widget: 'string', default: 'Hugo' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }